zextras/carbonio-ui-commons

hooks/use-folders-controller.ts, soap/get-folder.ts, soap/get-share-info.ts
feat: exposing get-folder and get-share-info api
=> feat: expose hook to manage folders

test/mocks/folders/folders-generator.ts
=> fix: fix the folders mock structure

test/mocks/carbonio-shell-ui.tsx
Add a mocked implementation for the tags getters and hooks (_getTag_, _getTags_, _useTag_, _useTags_)
=> test: add mocks for tags getters and hooks

test/mocks/carbonio-shell-ui.tsx
=> test: add shell mocks

test/mocks/network/msw/create-api-interceptor.ts
- Now api interceptor can send response
=> refactor: change api interceptor to get response

helpers/folders.test.ts, helpers/folders.ts
=> fear: add functions to check permissions on folders links

hooks/use-update-view.test.ts, hooks/use-update-view.ts, soap/no-op.test.ts, soap/no-op.ts
=> feat: add noop API request function

test/mocks/network/msw/create-api-interceptor.ts
now it can handle more than one single request
=> test: improve API interceptor

test/i18n/i18n-test-factory.ts
Refs: IRIS-5158
Require #122 to be merged first
=> refactor: change the i18next configuration for the test wrapper

components/select/folders-selector.tsx, helpers/folders.test.ts, helpers/folders.ts, test/mocks/folders/folders-generator.ts
=> feat: folders selector improvements

helpers/email-parser.ts, helpers/tests/email-parser.test.ts
- added more test cases not previously covered
- fixed the regex in order to handle all these cases
=> fix email validation

soap/no-op.test.ts, test/mocks/network/fetch.ts, test/mocks/utils/soap.ts
Update test related code to reflect the new `SoapFault` type provided by Shell
Refs: CO-1267
=> refactor(type): alignment for the new SoapFault type

test/mocks/accounts/account-generator.ts, test/mocks/accounts/default-account.ts
=> chore: make compatible the account generator with custom

soap/get-share-info.ts
=> refactor: export types

test/mocks/carbonio-shell-ui.tsx
Adds a default mock for the `useActions` hook
Refs: CO-1506
=> test: add useActions mock

components/breadcrumbs/static-breadcrumbs.tsx
This PR fixes the previous one which caused failing tests on Contacts
Refs: CO-1619
=> fix: remove useless forwardRef

types/sidebar/index.d.ts
See also: https://github.com/zextras/carbonio-mails-ui/pull/886
Ref: CO-2039
=> fix: moved types to mails module

test/mocks/utils/window.ts
Required for [Mails PR #810](https://github.com/zextras/carbonio-mails-ui/pull/810)
=> test: add a mock utility for window location

components/select/color-select.tsx
=> fix: colors list translations

constants/search.ts, helpers/search.ts, helpers/tests/search.test.ts
=> feat: add search util for converting chip to string

test/mocks/carbonio-shell-ui.tsx
=> test(mocks): add board related functions mocks

test/mocks/folders/folders-generator.ts
required for adding test for [CO-1983]
[CO-1983]: https://zextras.atlassian.net/browse/CO-1983?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: add u(unread in folder) in generateFolder test util
